In [1]:

import numpy as np
# Simple operation on array
A = np.array([10,20,30,40])
print("only one element : ",A[2]) # 2nd indexed element
print("Index form last : ",A[-1]) # negetive index means elements from last

only one element :  30
Index form last :  40


In [2]:
import numpy as np
# multidimentional array
A = np.array([[12,2,3],[20,1,4],[90,2,3]])
print(A)
print("sigle ele from multidimentional array : ",A[0,2])

#in loop
for i in range(A.shape[0]): # use shape got multidimension array
    for j in range(A.shape[1]):
        print(A[i,j], end = " ")
    print()

[[12  2  3]
 [20  1  4]
 [90  2  3]]
sigle ele from multidimentional array :  3
12 2 3 
20 1 4 
90 2 3 


In [3]:

import numpy as np

A = np.array([1,2],dtype = float)
print(A)
print(A.dtype)

[1. 2.]
float64


In [4]:
import numpy as np

A = np.zeros((3,3))
print(A)
A = np.ones((2,2))
print(A)
A = np.arange(0,10,3)
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 3 6 9]


In [5]:

import numpy as np
A = np.array([
    [1,2,3,4],
    [5,6,7,8]]
)
A = A[:2, ::1]
print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:

#are there zeros in a array
import numpy as np
arr1 = np.array([1,3,5,3,2])
arr2 = np.array([1,0,3,5,2])

zeros_in_arr1 = np.all(arr1 != 0)
zeros_in_arr2 = np.all(arr2 != 0)
print("Are there zeros in array 1 : ", zeros_in_arr1)
print("Are there zeros in array 2 : ", zeros_in_arr2)

Are there zeros in array 1 :  True
Are there zeros in array 2 :  False


In [7]:
#Print boolen array for the greater / smaller /  equal
import numpy as np
arr1 = np.array([10,80,30,40])
arr2 = np.array([10,20,30,50])
print("Greater array 1 : ", arr1 > arr2)
print("Smaller array 1 : ", arr1 < arr2)
print("Equal array 1 : ", arr1 == arr2)

Greater array 1 :  [False  True False False]
Smaller array 1 :  [False False False  True]
Equal array 1 :  [ True False  True False]


In [9]:
#filter the data in the range of a min value and a max value
import numpy as np
raw_data = np.array([12,3,1,5,8,32,5,9,23,90,67])
min_range = 5
max_range = 15
print("The Raw data : ", raw_data)
filter_data = raw_data[(raw_data >= min_range) & (raw_data <= max_range)]
print("Filtered out data : ",filter_data)

The Raw data :  [12  3  1  5  8 32  5  9 23 90 67]
Filtered out data :  [12  5  8  5  9]


In [10]:
import numpy as np

# Create a sample 2D NumPy array
arr = np.array([[10, 20, 5],
                [15, 3, 25],
                [30, 8, 12]])

print("Original array:")
print(arr)

# Find the indices of the maximum values along each row (axis=1)
max_indices = np.argmax(arr, axis=1)

# Find the indices of the minimum values along each row (axis=1)
min_indices = np.argmin(arr, axis=1)

print("\nIndices of the maximum values along each row:", max_indices)
print("Indices of the minimum values along each row:", min_indices)

# To verify, you can use these indices to get the actual max and min values
max_values = arr[np.arange(len(arr)), max_indices]
min_values = arr[np.arange(len(arr)), min_indices]

print("\nMaximum values:", max_values)
print("Minimum values:", min_values)

Original array:
[[10 20  5]
 [15  3 25]
 [30  8 12]]

Indices of the maximum values along each row: [1 2 0]
Indices of the minimum values along each row: [2 1 1]

Maximum values: [20 25 30]
Minimum values: [5 3 8]
